load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")
package(default_visibility = ["//visibility:public"])

cuda_library(
    name = "kernel",
    srcs = ["kernel.cu"],
    hdrs = ["kernel.h"],
)
cuda_library(
    name = "vector_addition",
    srcs = ["vector_addition.cu"],
)
cc_binary(
  name = "vector_addition_bin",
  deps = [":vector_addition"]
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [":kernel"],
)
cuda_library(
    name = "hello_cuda_lib",
    srcs = ["cuda_hello_world.cu"],
)
cc_binary(
    name = "basic-algorithms",
    srcs = ["basic-algorithms.cpp"],
)

cc_binary(
    name = "cuda_hello_world",
    deps = [":hello_cuda_lib"],
)
